# Generated by Django 5.1.4 on 2024-12-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("information", models.TextField()),
                ("datetime_create", models.DateTimeField(auto_now_add=True)),
                ("datetime_update", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pub", "انتشار یافته"), ("drf", "پیش نمایش")],
                        max_length=3,
                    ),
                ),
            ],
        ),
    ]
